# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
city_weather = "../WeatherPy/output_data/city_weather.csv"
city_weather_df=pd.read_csv(city_weather)
city_weather_df

,City,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind,Country,Date
0,ushuaia,-54.8000,-68.3000,55.40,54,20,18.41,AR,1612705770
1,busselton,-33.6500,115.3333,62.01,97,100,1.01,AU,1612705857
2,port elizabeth,-33.9180,25.5701,69.80,94,75,9.22,ZA,1612705857
3,kodiak,57.7900,-152.4072,26.60,63,75,4.61,US,1612705565
4,new norfolk,-42.7826,147.0587,55.40,62,90,4.61,AU,1612705858
...,...,...,...,...,...,...,...,...,...
577,umarkot,25.3616,69.7362,64.80,28,0,1.45,PK,1612705918
578,chegdomyn,51.1167,133.0167,-13.49,88,97,0.63,RU,1612705918
579,buala,-8.1450,159.5921,78.66,82,100,3.02,SB,1612705918
580,vapi,20.3718,72.9049,74.37,39,0,7.09,IN,1612705918
581,orocue,4.7912,-71.3354,86.22,54,100,11.23,CO,1612705918

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
# Store latitude and longitude in locations
city_weather_df=city_weather_df.dropna()
locations =city_weather_df[["Lat", "Lng"]].astype(float)
Humidity=city_weather_df["Humidity"].astype(float)
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=Humidity, 
                                 dissipating=False, max_intensity=max(city_weather_df["Humidity"]),
                                 point_radius=2)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
city_weather_df.dtypes

City           object
Lat           float64
Lng           float64
Max_Temp      float64
Humidity        int64
Cloudiness      int64
Wind          float64
Country        object
Date            int64
dtype: object

In [6]:
#Narrow down the DataFrame to find your ideal weather condition. For example:
#A max temperature lower than 90 degrees but higher than 70.
#Wind speed less than 10 mph.
#Zero cloudiness.
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.
New_city_weather_df=city_weather_df.loc[ (city_weather_df["Max_Temp"]>70) & (city_weather_df["Max_Temp"]< 90) & (city_weather_df["Wind"]<10) &(city_weather_df["Cloudiness"]==0)]
New_city_weather_df

,City,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind,Country,Date
15,uruguaiana,-29.7547,-57.0883,78.80,65,0,6.91,BR,1612705859
50,ancud,-41.8697,-73.8203,73.00,55,0,8.05,CL,1612705864
59,chuy,-33.6971,-53.4616,75.31,59,0,5.61,UY,1612705864
77,nicoya,10.1483,-85.4520,71.60,88,0,2.30,CR,1612705866
252,kavaratti,10.5669,72.6420,81.70,66,0,8.66,IN,1612705884
255,abu dhabi,24.4667,54.3667,80.60,32,0,8.05,AE,1612705635
281,florianopolis,-27.6146,-48.5012,82.99,61,0,4.61,BR,1612705888
286,san lorenzo,-25.3333,-57.5333,82.40,54,0,5.75,PY,1612705888
299,phitsanulok,16.9167,100.5000,89.01,73,0,2.30,TH,1612705889
303,mecca,21.4267,39.8261,81.21,17,0,8.34,SA,1612705890
319,macherla,16.4833,79.4333,75.97,38,0,2.15,IN,1612705892
320,rocha,-34.4833,-54.3333,76.77,56,0,4.18,UY,1612705892
388,illapel,-31.6308,-71.1653,71.89,44,0,5.64,CL,1612705899
454,fayaoue,-20.6500,166.5333,80.31,73,0,6.40,NC,1612705822
470,tabas,33.5959,56.9244,73.40,13,0,2.30,IR,1612705907
479,oussouye,12.4850,-16.5469,84.20,30,0,6.91,SN,1612705908
481,coxim,-18.5067,-54.7600,83.77,50,0,6.13,BR,1612705908
496,iquique,-20.2208,-70.1431,77.00,47,0,8.05,CL,1612705910
508,khairpur,27.5295,68.7617,77.00,50,0,7.56,PK,1612705911
515,castro,-24.7911,-50.0119,70.02,52,0,4.16,BR,1612705912
532,mul,20.0667,79.6667,70.54,22,0,6.20,IN,1612705913
546,dolores,-36.3132,-57.6792,80.62,51,0,3.71,AR,1612705915
549,santa vitoria do palmar,-33.5189,-53.3681,75.60,59,0,4.52,BR,1612705834
560,payyannur,12.1000,75.2000,77.16,72,0,5.03,IN,1612705916
576,luxor,25.6989,32.6421,78.80,34,0,4.61,EG,1612705918
580,vapi,20.3718,72.9049,74.37,39,0,7.09,IN,1612705918

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotel_df = New_city_weather_df
hotel_df["Hotel Name"]=""
hotel_df

<ipython-input-7-1c165389b801>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"]=""

,City,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind,Country,Date,Hotel Name
15,uruguaiana,-29.7547,-57.0883,78.80,65,0,6.91,BR,1612705859,
50,ancud,-41.8697,-73.8203,73.00,55,0,8.05,CL,1612705864,
59,chuy,-33.6971,-53.4616,75.31,59,0,5.61,UY,1612705864,
77,nicoya,10.1483,-85.4520,71.60,88,0,2.30,CR,1612705866,
252,kavaratti,10.5669,72.6420,81.70,66,0,8.66,IN,1612705884,
255,abu dhabi,24.4667,54.3667,80.60,32,0,8.05,AE,1612705635,
281,florianopolis,-27.6146,-48.5012,82.99,61,0,4.61,BR,1612705888,
286,san lorenzo,-25.3333,-57.5333,82.40,54,0,5.75,PY,1612705888,
299,phitsanulok,16.9167,100.5000,89.01,73,0,2.30,TH,1612705889,
303,mecca,21.4267,39.8261,81.21,17,0,8.34,SA,1612705890,
319,macherla,16.4833,79.4333,75.97,38,0,2.15,IN,1612705892,
320,rocha,-34.4833,-54.3333,76.77,56,0,4.18,UY,1612705892,
388,illapel,-31.6308,-71.1653,71.89,44,0,5.64,CL,1612705899,
454,fayaoue,-20.6500,166.5333,80.31,73,0,6.40,NC,1612705822,
470,tabas,33.5959,56.9244,73.40,13,0,2.30,IR,1612705907,
479,oussouye,12.4850,-16.5469,84.20,30,0,6.91,SN,1612705908,
481,coxim,-18.5067,-54.7600,83.77,50,0,6.13,BR,1612705908,
496,iquique,-20.2208,-70.1431,77.00,47,0,8.05,CL,1612705910,
508,khairpur,27.5295,68.7617,77.00,50,0,7.56,PK,1612705911,
515,castro,-24.7911,-50.0119,70.02,52,0,4.16,BR,1612705912,
532,mul,20.0667,79.6667,70.54,22,0,6.20,IN,1612705913,
546,dolores,-36.3132,-57.6792,80.62,51,0,3.71,AR,1612705915,
549,santa vitoria do palmar,-33.5189,-53.3681,75.60,59,0,4.52,BR,1612705834,
560,payyannur,12.1000,75.2000,77.16,72,0,5.03,IN,1612705916,
576,luxor,25.6989,32.6421,78.80,34,0,4.61,EG,1612705918,
580,vapi,20.3718,72.9049,74.37,39,0,7.09,IN,1612705918,

In [9]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] =results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 15: uruguaiana.
Missing field/result... skipping.
------------
Retrieving Results for Index 50: ancud.
Closest hotel is Hotel Arena Gruesa.
------------
Retrieving Results for Index 59: chuy.
Missing field/result... skipping.
------------
Retrieving Results for Index 77: nicoya.

C:\Users\gsun\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

Closest hotel is Guayacan Real.
------------
Retrieving Results for Index 252: kavaratti.
Closest hotel is Hotels in Lakshadweep Islands.
------------
Retrieving Results for Index 255: abu dhabi.
Closest hotel is Beach Rotana.
------------
Retrieving Results for Index 281: florianopolis.
Missing field/result... skipping.
------------
Retrieving Results for Index 286: san lorenzo.
Closest hotel is Canarias Hotel.
------------
Retrieving Results for Index 299: phitsanulok.
Missing field/result... skipping.
------------
Retrieving Results for Index 303: mecca.
Missing field/result... skipping.
------------
Retrieving Results for Index 319: macherla.
Closest hotel is Vivek express.
------------
Retrieving Results for Index 320: rocha.
Closest hotel is Beleza Pura B&B.
------------
Retrieving Results for Index 388: illapel.
Closest hotel is Hotel Londres.
------------
Retrieving Results for Index 454: fayaoue.
Closest hotel is Chez Dydyce Guesthouse.
------------
Retrieving Results for Index 470: tabas.
Closest hotel is Ø´Ø±Ú©Øª Ù…Ø¹Ù…Ø§Ø±ÛŒ Ù…Ù‡Ø±Ø§Ø² Ø´Ø§ÛŒÚ¯Ø§Ù† Ø¢Ø±Ø§Ø¯.
------------
Retrieving Results for Index 479: oussouye.
Closest hotel is Auberge du Routard.
------------
Retrieving Results for Index 481: coxim.
Closest hotel is Hotel Avenida.
------------
Retrieving Results for Index 496: iquique.
Closest hotel is Backpacker`s Hostel Iquique.
------------
Retrieving Results for Index 508: khairpur.
Closest hotel is Khaskheli house Wafa Fida.
------------
Retrieving Results for Index 515: castro.
Closest hotel is CHACARA BAILLY.
------------
Retrieving Results for Index 532: mul.
Closest hotel is Taj Mahal.
------------
Retrieving Results for Index 546: dolores.
Closest hotel is Apart Hotel - Arianos.
------------
Retrieving Results for Index 549: santa vitoria do palmar.
Closest hotel is Hostel Comodoro.
------------
Retrieving Results for Index 560: payyannur.
Closest hotel is Kavvayi Beach House.
------------
Retrieving Results for Index 576: luxor.
Closest hotel is Iberotel Luxor.
------------
Retrieving Results for Index 580: vapi.
Closest hotel is hotel Dan.
------------

In [10]:
hotel_df

,City,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind,Country,Date,Hotel Name
15,uruguaiana,-29.7547,-57.0883,78.80,65,0,6.91,BR,1612705859,
50,ancud,-41.8697,-73.8203,73.00,55,0,8.05,CL,1612705864,Hotel Arena Gruesa
59,chuy,-33.6971,-53.4616,75.31,59,0,5.61,UY,1612705864,
77,nicoya,10.1483,-85.4520,71.60,88,0,2.30,CR,1612705866,Guayacan Real
252,kavaratti,10.5669,72.6420,81.70,66,0,8.66,IN,1612705884,Hotels in Lakshadweep Islands
255,abu dhabi,24.4667,54.3667,80.60,32,0,8.05,AE,1612705635,Beach Rotana
281,florianopolis,-27.6146,-48.5012,82.99,61,0,4.61,BR,1612705888,
286,san lorenzo,-25.3333,-57.5333,82.40,54,0,5.75,PY,1612705888,Canarias Hotel
299,phitsanulok,16.9167,100.5000,89.01,73,0,2.30,TH,1612705889,
303,mecca,21.4267,39.8261,81.21,17,0,8.34,SA,1612705890,
319,macherla,16.4833,79.4333,75.97,38,0,2.15,IN,1612705892,Vivek express
320,rocha,-34.4833,-54.3333,76.77,56,0,4.18,UY,1612705892,Beleza Pura B&B
388,illapel,-31.6308,-71.1653,71.89,44,0,5.64,CL,1612705899,Hotel Londres
454,fayaoue,-20.6500,166.5333,80.31,73,0,6.40,NC,1612705822,Chez Dydyce Guesthouse
470,tabas,33.5959,56.9244,73.40,13,0,2.30,IR,1612705907,Ø´Ø±Ú©Øª Ù…Ø¹Ù…Ø§Ø±ÛŒ Ù…Ù‡Ø±Ø§Ø² Ø´Ø§ÛŒÚ¯Ø§Ù† Ø¢Ø±Ø§Ø¯
479,oussouye,12.4850,-16.5469,84.20,30,0,6.91,SN,1612705908,Auberge du Routard
481,coxim,-18.5067,-54.7600,83.77,50,0,6.13,BR,1612705908,Hotel Avenida
496,iquique,-20.2208,-70.1431,77.00,47,0,8.05,CL,1612705910,Backpacker`s Hostel Iquique
508,khairpur,27.5295,68.7617,77.00,50,0,7.56,PK,1612705911,Khaskheli house Wafa Fida
515,castro,-24.7911,-50.0119,70.02,52,0,4.16,BR,1612705912,CHACARA BAILLY
532,mul,20.0667,79.6667,70.54,22,0,6.20,IN,1612705913,Taj Mahal
546,dolores,-36.3132,-57.6792,80.62,51,0,3.71,AR,1612705915,Apart Hotel - Arianos
549,santa vitoria do palmar,-33.5189,-53.3681,75.60,59,0,4.52,BR,1612705834,Hostel Comodoro
560,payyannur,12.1000,75.2000,77.16,72,0,5.03,IN,1612705916,Kavvayi Beach House
576,luxor,25.6989,32.6421,78.80,34,0,4.61,EG,1612705918,Iberotel Luxor
580,vapi,20.3718,72.9049,74.37,39,0,7.09,IN,1612705918,hotel Dan

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [13]:
# Assign the marker layer to a variable
locations = hotel_df[["Lat", "Lng"]]
markers = gmaps.marker_layer(locations)


# Add marker layer ontop of heat map
# Create hotel symbol layer
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
)
# Add the layer to the map
fig.add_layer(markers)
fig.add_layer(hotel_layer)


# Display figure
fig

Figure(layout=FigureLayout(height='420px'))